version: '3.9'

services:
  redis:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning


  backend:
    build: .
    container_name: django_backend
    command: [ "python","manage.py","runserver","0.0.0.0:8000" ]
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=test
      - DEBUG=ture
    depends_on:
      - redis
  smtp4dev:
    image: rnwood/smtp4dev:v3
    container_name: smtp4dev
    restart: always
    ports:
      - "5000:80"
      - "25:25"
      - "143:143"
    volumes:
      - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__Urls=http://*:80
      - ServerOptions__HostName=smtp4dev
  worker:
    build: .
    command: celery -A NFTAPI worker --loglevel=info
    depends_on:
      - redis
      - backend
    volumes:
      - .:/app
volumes:
  smtpdev-data:


